version: "3"
services:
  redis:
    container_name: redis
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"
  rust-ticker-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
